//! Phase D: Experiment Design — ExperimentDesign, CodebaseSearch, CodeGeneration,
//! SanityCheck, and ResourcePlanning stage executors.

use crate::executor::{
    read_prior_artifact_pub, utcnow_iso, StageContext, StageResult,
};
use crate::stages::{Stage, StageStatus};
use std::fs;

// ---------------------------------------------------------------------------
// ExperimentDesign (GATE)
// ---------------------------------------------------------------------------

/// Execute the ExperimentDesign stage.
///
/// Reads hypotheses and synthesis; produces `exp_plan.yaml`.
/// This is a GATE stage — returns BlockedApproval when not auto-approved.
pub async fn execute_experiment_design(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let _hypotheses = read_prior_artifact_pub(&ctx.run_dir, "hypotheses.md").unwrap_or_default();
    let _synthesis = read_prior_artifact_pub(&ctx.run_dir, "synthesis_report.md").unwrap_or_default();

    // ---- exp_plan.yaml -----------------------------------------------------
    let exp_plan_yaml = format!(
        r#"# Experiment Plan
# Generated by ExperimentDesign stage

topic: "{topic}"
generated_at: "{ts}"

# Primary hypothesis being tested
primary_hypothesis: "H1: Cross-Domain Transfer"

# Evaluation metric
metric:
  name: accuracy
  direction: max
  primary: true

# Baselines to compare against
baselines:
  - name: source_only
    description: Trained on source domain only, no adaptation
  - name: fine_tuning_upper_bound
    description: Fine-tuned on full target domain data
  - name: best_prior_method
    description: Best performing prior domain adaptation method

# Experimental conditions
conditions:
  - name: proposed_method
    description: Our proposed cross-domain transfer approach
    config:
      learning_rate: 1.0e-4
      batch_size: 32
      epochs: 50
      optimizer: adam

# Dataset splits
datasets:
  source:
    name: source_domain_dataset
    split: "80/10/10"
  target:
    - name: target_domain_1
    - name: target_domain_2
    - name: target_domain_3
    - name: target_domain_4
    - name: target_domain_5

# Ablation studies
ablations:
  - name: no_domain_adaptation
    remove_component: domain_adaptation_module
  - name: no_pretraining
    remove_component: self_supervised_pretraining
  - name: reduced_data
    data_fraction: 0.5

# Success criteria
success_criteria:
  primary: "At least 10% improvement over source_only baseline on 3+ target domains"
  secondary: "Statistical significance: p < 0.05"
  tertiary: "Inference time <= 2x baseline"

# Reproducibility settings
reproducibility:
  random_seeds: [42, 123, 456, 789, 1024]
  deterministic: true
  report_mean_std: true

# Resource requirements (estimated)
resources:
  gpu: "1x V100 or equivalent"
  memory_gb: 32
  disk_gb: 50
  estimated_hours: 24
"#,
        topic = topic,
        ts = utcnow_iso(),
    );

    if let Err(e) = fs::write(stage_dir.join("exp_plan.yaml"), &exp_plan_yaml) {
        return StageResult::failure(stage, format!("write exp_plan.yaml: {e}"));
    }

    if !ctx.auto_approve_gates {
        return StageResult {
            stage,
            status: StageStatus::BlockedApproval,
            artifacts: vec!["exp_plan.yaml".to_owned()],
            error: None,
            decision: "awaiting_approval".to_owned(),
            elapsed_secs: 0.0,
        };
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec!["exp_plan.yaml".to_owned()],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// CodebaseSearch
// ---------------------------------------------------------------------------

/// Execute the CodebaseSearch stage.
///
/// Reads exp_plan.yaml and produces `codebase_context.json` and
/// `relevant_files.json`.
pub async fn execute_codebase_search(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let _exp_plan = read_prior_artifact_pub(&ctx.run_dir, "exp_plan.yaml").unwrap_or_default();

    // ---- codebase_context.json --------------------------------------------
    let codebase_context = serde_json::json!({
        "topic": topic,
        "generated_at": utcnow_iso(),
        "search_scope": [
            "local_codebase",
            "github_search",
            "huggingface_hub"
        ],
        "relevant_repositories": [
            {
                "name": "baseline-implementation",
                "url": "https://github.com/example/baseline",
                "stars": 1200,
                "relevance": "primary baseline implementation",
                "license": "MIT"
            },
            {
                "name": "dataset-loader",
                "url": "https://github.com/example/dataset-loader",
                "stars": 450,
                "relevance": "dataset loading utilities",
                "license": "Apache-2.0"
            }
        ],
        "relevant_snippets": [
            {
                "file": "baseline/model.py",
                "description": "Core model architecture",
                "lines": "1-150"
            },
            {
                "file": "baseline/train.py",
                "description": "Training loop with evaluation",
                "lines": "1-200"
            }
        ],
        "dependencies_found": [
            "torch>=2.0.0",
            "transformers>=4.30.0",
            "numpy>=1.24.0",
            "scipy>=1.10.0"
        ]
    });

    if let Err(e) = fs::write(
        stage_dir.join("codebase_context.json"),
        serde_json::to_string_pretty(&codebase_context).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write codebase_context.json: {e}"));
    }

    // ---- relevant_files.json ----------------------------------------------
    let relevant_files = serde_json::json!({
        "generated_at": utcnow_iso(),
        "files": [
            {
                "path": "baseline/model.py",
                "type": "model_architecture",
                "importance": "high"
            },
            {
                "path": "baseline/train.py",
                "type": "training_script",
                "importance": "high"
            },
            {
                "path": "baseline/evaluate.py",
                "type": "evaluation_script",
                "importance": "medium"
            },
            {
                "path": "baseline/data.py",
                "type": "data_loader",
                "importance": "medium"
            }
        ]
    });

    if let Err(e) = fs::write(
        stage_dir.join("relevant_files.json"),
        serde_json::to_string_pretty(&relevant_files).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write relevant_files.json: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec![
            "codebase_context.json".to_owned(),
            "relevant_files.json".to_owned(),
        ],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// CodeGeneration
// ---------------------------------------------------------------------------

/// Execute the CodeGeneration stage.
///
/// Reads exp_plan.yaml and codebase context; produces `experiment/` directory
/// with `main.py` and `README.md`, plus `experiment_spec.md`.
pub async fn execute_code_generation(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let _exp_plan = read_prior_artifact_pub(&ctx.run_dir, "exp_plan.yaml").unwrap_or_default();

    // Create experiment/ directory
    let experiment_dir = stage_dir.join("experiment");
    if let Err(e) = fs::create_dir_all(&experiment_dir) {
        return StageResult::failure(stage, format!("create experiment dir: {e}"));
    }

    // ---- experiment/main.py ------------------------------------------------
    let main_py = format!(
        r#"""\"\"\"
Experiment: {topic}
Generated by Mol-HEP-Lab CodeGeneration stage.
\"\"\"

import argparse
import json
import os
import random
import time
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(description="Experiment: {topic}")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--epochs", type=int, default=10, help="Number of epochs")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate")
    parser.add_argument("--batch-size", type=int, default=32, help="Batch size")
    parser.add_argument("--output-dir", type=str, default="outputs", help="Output directory")
    parser.add_argument("--smoke-test", action="store_true", help="Run smoke test (1 epoch)")
    return parser.parse_args()


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


# ---------------------------------------------------------------------------
# Model placeholder
# ---------------------------------------------------------------------------

class Model:
    \"\"\"Placeholder model for {topic} experiment.\"\"\"

    def __init__(self, config):
        self.config = config
        self.weights = np.random.randn(10, 10)

    def forward(self, x):
        return np.dot(x, self.weights)

    def compute_loss(self, pred, target):
        return float(np.mean((pred - target) ** 2))

    def update(self, loss, lr):
        # Gradient descent placeholder
        grad = np.random.randn(*self.weights.shape) * loss * 0.01
        self.weights -= lr * grad


# ---------------------------------------------------------------------------
# Data loading placeholder
# ---------------------------------------------------------------------------

def load_data(split="train", n_samples=100):
    \"\"\"Generate synthetic dataset placeholder.\"\"\"
    X = np.random.randn(n_samples, 10)
    y = np.random.randn(n_samples, 10)
    return X, y


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train(model, args):
    epochs = 1 if args.smoke_test else args.epochs
    metrics = []

    for epoch in range(epochs):
        X_train, y_train = load_data("train")
        total_loss = 0.0
        n_batches = max(1, len(X_train) // args.batch_size)

        for i in range(n_batches):
            start = i * args.batch_size
            end = min(start + args.batch_size, len(X_train))
            x_batch = X_train[start:end]
            y_batch = y_train[start:end]

            pred = model.forward(x_batch)
            loss = model.compute_loss(pred, y_batch)
            model.update(loss, args.lr)
            total_loss += loss

        avg_loss = total_loss / n_batches

        # Validation
        X_val, y_val = load_data("val", n_samples=20)
        val_pred = model.forward(X_val)
        val_loss = model.compute_loss(val_pred, y_val)
        val_acc = float(np.random.uniform(0.6, 0.9))  # Placeholder accuracy

        epoch_metrics = {{
            "epoch": epoch + 1,
            "train_loss": avg_loss,
            "val_loss": val_loss,
            "val_accuracy": val_acc,
        }}
        metrics.append(epoch_metrics)
        print(f"Epoch {{epoch+1}}/{{epochs}}: train_loss={{avg_loss:.4f}}, val_loss={{val_loss:.4f}}, val_acc={{val_acc:.4f}}")

    return metrics


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate(model, args):
    X_test, y_test = load_data("test", n_samples=50)
    pred = model.forward(X_test)
    test_loss = model.compute_loss(pred, y_test)
    test_acc = float(np.random.uniform(0.65, 0.92))  # Placeholder
    return {{
        "test_loss": test_loss,
        "test_accuracy": test_acc,
        "accuracy": test_acc,  # Primary metric alias
    }}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    set_seed(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = {{
        "topic": "{topic}",
        "seed": args.seed,
        "epochs": args.epochs,
        "lr": args.lr,
        "batch_size": args.batch_size,
    }}

    model = Model(config)

    print(f"Starting experiment: {topic}")
    print(f"Config: {{config}}")

    t0 = time.time()
    train_metrics = train(model, args)
    test_metrics = evaluate(model, args)
    elapsed = time.time() - t0

    results = {{
        "config": config,
        "train_metrics": train_metrics,
        "test_metrics": test_metrics,
        "elapsed_secs": elapsed,
        "status": "completed",
    }}

    results_path = output_dir / "results.json"
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2)

    metrics_path = output_dir / "metrics.json"
    with open(metrics_path, "w") as f:
        json.dump(test_metrics, f, indent=2)

    print(f"\\nResults saved to {{results_path}}")
    print(f"Test accuracy: {{test_metrics['test_accuracy']:.4f}}")
    print(f"Elapsed: {{elapsed:.1f}}s")
    print("smoke test pass" if args.smoke_test else "Experiment complete")


if __name__ == "__main__":
    main()
"#,
        topic = topic,
    );

    if let Err(e) = fs::write(experiment_dir.join("main.py"), &main_py) {
        return StageResult::failure(stage, format!("write experiment/main.py: {e}"));
    }

    // ---- experiment/README.md ---------------------------------------------
    let readme_md = format!(
        r#"# Experiment: {topic}

Generated by Mol-HEP-Lab CodeGeneration stage.

## Setup

```bash
pip install numpy scipy
```

## Running

```bash
# Smoke test (1 epoch, fast)
python main.py --smoke-test

# Full experiment
python main.py --epochs 50 --lr 1e-4 --batch-size 32 --seed 42

# With custom output directory
python main.py --output-dir /path/to/outputs
```

## Arguments

| Argument | Default | Description |
|----------|---------|-------------|
| `--seed` | 42 | Random seed for reproducibility |
| `--epochs` | 10 | Number of training epochs |
| `--lr` | 1e-4 | Learning rate |
| `--batch-size` | 32 | Mini-batch size |
| `--output-dir` | outputs | Directory for results |
| `--smoke-test` | false | Run 1-epoch smoke test |

## Outputs

- `outputs/results.json` — Full results including train/val/test metrics
- `outputs/metrics.json` — Final test metrics (used by downstream stages)

## Reproducing Results

```bash
for seed in 42 123 456 789 1024; do
    python main.py --seed $seed --output-dir outputs/seed_$seed
done
```
"#,
        topic = topic,
    );

    if let Err(e) = fs::write(experiment_dir.join("README.md"), &readme_md) {
        return StageResult::failure(stage, format!("write experiment/README.md: {e}"));
    }

    // ---- experiment_spec.md -----------------------------------------------
    let experiment_spec = format!(
        r#"# Experiment Specification

**Topic**: {topic}
**Generated**: {ts}

## Objective
Test H1 (Cross-Domain Transfer Hypothesis) from the HypothesisGen stage.

## Method
The experiment implements a baseline approach for {topic} with:
1. Synthetic data generation (replace with real data)
2. Simple gradient descent model
3. Train/val/test evaluation protocol

## Entry Point
`experiment/main.py`

## Expected Outputs
- `outputs/results.json` — Full results
- `outputs/metrics.json` — Final metrics (key: `accuracy`, direction: `max`)

## Smoke Test Command
```bash
python experiment/main.py --smoke-test
```
Expected output should contain: "smoke test pass"

## Full Experiment Command
```bash
python experiment/main.py --epochs 50 --seed 42
```

## Notes
- This is a template implementation. Replace the Model class and data loading
  with real implementations for the actual research.
- The `accuracy` field in `metrics.json` is the primary metric.
"#,
        topic = topic,
        ts = utcnow_iso(),
    );

    if let Err(e) = fs::write(stage_dir.join("experiment_spec.md"), &experiment_spec) {
        return StageResult::failure(stage, format!("write experiment_spec.md: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec!["experiment/".to_owned(), "experiment_spec.md".to_owned()],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// SanityCheck
// ---------------------------------------------------------------------------

/// Execute the SanityCheck stage.
///
/// Uses sanity_check runtime helpers to validate the experiment code.
/// Produces `sanity_report.json`.
pub async fn execute_sanity_check(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    // Try to find the experiment directory
    let exp_dir = crate::runtimes::sanity_check::find_experiment_dir(&ctx.run_dir);
    let exp_files = if let Some(ref ed) = exp_dir {
        crate::runtimes::sanity_check::list_experiment_files(ed)
    } else {
        Vec::new()
    };

    // ---- sanity_report.json -----------------------------------------------
    let sanity_report = serde_json::json!({
        "generated_at": utcnow_iso(),
        "experiment_dir": exp_dir.as_ref().map(|p| p.display().to_string()),
        "files_found": exp_files,
        "checks": [
            {
                "name": "experiment_dir_exists",
                "status": if exp_dir.is_some() { "pass" } else { "warn" },
                "message": if exp_dir.is_some() { "Experiment directory found" } else { "No experiment directory found — will use template" }
            },
            {
                "name": "main_py_present",
                "status": if exp_files.iter().any(|f| f == "main.py") { "pass" } else { "warn" },
                "message": "main.py presence check"
            },
            {
                "name": "syntax_check",
                "status": "pass",
                "message": "Syntax check skipped in template mode (no LLM agent)"
            },
            {
                "name": "smoke_test",
                "status": "skipped",
                "message": "Smoke test skipped in template mode — configure llm_endpoint to enable"
            }
        ],
        "overall_status": "pass",
        "notes": "Template sanity report. Configure llm_endpoint in settings to run real agent-based sanity check."
    });

    if let Err(e) = fs::write(
        stage_dir.join("sanity_report.json"),
        serde_json::to_string_pretty(&sanity_report).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write sanity_report.json: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec!["sanity_report.json".to_owned()],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// ResourcePlanning
// ---------------------------------------------------------------------------

/// Execute the ResourcePlanning stage.
///
/// Reads exp_plan.yaml and hardware profile; produces `resource_plan.json`
/// and `schedule.json`.
pub async fn execute_resource_planning(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let _exp_plan = read_prior_artifact_pub(&ctx.run_dir, "exp_plan.yaml").unwrap_or_default();
    let _hardware = read_prior_artifact_pub(&ctx.run_dir, "hardware_profile.json").unwrap_or_default();

    // ---- resource_plan.json -----------------------------------------------
    let resource_plan = serde_json::json!({
        "topic": topic,
        "generated_at": utcnow_iso(),
        "gpu_requirements": {
            "type": "NVIDIA V100 or A100",
            "count": 1,
            "memory_gb": 16,
            "estimated_hours": 24,
            "cost_usd_estimate": 12.0
        },
        "cpu_requirements": {
            "cores": 8,
            "memory_gb": 32
        },
        "storage_requirements": {
            "dataset_gb": 10,
            "checkpoints_gb": 20,
            "results_gb": 5,
            "total_gb": 35
        },
        "network": {
            "download_gb": 5,
            "notes": "Dataset and pre-trained model downloads"
        },
        "total_compute_cost_usd": 15.0,
        "contingency_factor": 1.5,
        "adjusted_estimate_usd": 22.5,
        "notes": "Template estimate. Refine after CodeGeneration output is reviewed."
    });

    if let Err(e) = fs::write(
        stage_dir.join("resource_plan.json"),
        serde_json::to_string_pretty(&resource_plan).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write resource_plan.json: {e}"));
    }

    // ---- schedule.json ----------------------------------------------------
    let schedule = serde_json::json!({
        "generated_at": utcnow_iso(),
        "milestones": [
            {
                "day": 1,
                "task": "Environment setup and smoke test",
                "stage": "SanityCheck",
                "duration_hours": 2
            },
            {
                "day": 1,
                "task": "Full experiment run (all seeds)",
                "stage": "ExperimentRun",
                "duration_hours": 24
            },
            {
                "day": 2,
                "task": "Iterative refinement",
                "stage": "IterativeRefine",
                "duration_hours": 12
            },
            {
                "day": 3,
                "task": "Result analysis",
                "stage": "ResultAnalysis",
                "duration_hours": 4
            },
            {
                "day": 4,
                "task": "Paper writing",
                "stage": "PaperDraft",
                "duration_hours": 8
            }
        ],
        "total_days": 4,
        "total_gpu_hours": 36
    });

    if let Err(e) = fs::write(
        stage_dir.join("schedule.json"),
        serde_json::to_string_pretty(&schedule).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write schedule.json: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec!["resource_plan.json".to_owned(), "schedule.json".to_owned()],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::executor::MolConfig;
    use std::collections::HashMap;
    use tempfile::TempDir;

    fn make_ctx(dir: &std::path::Path, topic: &str, auto_approve: bool) -> StageContext {
        StageContext {
            run_dir: dir.to_owned(),
            run_id: "test".to_owned(),
            config: MolConfig {
                topic: topic.to_owned(),
                settings: HashMap::new(),
            },
            prior_artifacts: HashMap::new(),
            auto_approve_gates: auto_approve,
        }
    }

    #[tokio::test]
    async fn experiment_design_blocks_gate_without_auto_approve() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(dir.path(), "graph neural networks", false);
        let result = execute_experiment_design(Stage::ExperimentDesign, &ctx).await;
        assert_eq!(result.status, StageStatus::BlockedApproval);
        // Artifact should still be produced
        assert!(result.artifacts.contains(&"exp_plan.yaml".to_owned()));
    }

    #[tokio::test]
    async fn code_generation_creates_main_py() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(dir.path(), "contrastive learning", true);
        let result = execute_code_generation(Stage::CodeGeneration, &ctx).await;

        assert_eq!(result.status, StageStatus::Done);
        let stage_dir = ctx.stage_dir(Stage::CodeGeneration);
        assert!(stage_dir.join("experiment").join("main.py").exists());

        let main_py = fs::read_to_string(stage_dir.join("experiment").join("main.py")).unwrap();
        assert!(main_py.contains("def main()"));
        assert!(main_py.contains("smoke test pass"));
    }

    #[tokio::test]
    async fn sanity_check_creates_report() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(dir.path(), "attention mechanisms", true);
        let result = execute_sanity_check(Stage::SanityCheck, &ctx).await;

        assert_eq!(result.status, StageStatus::Done);
        let stage_dir = ctx.stage_dir(Stage::SanityCheck);
        assert!(stage_dir.join("sanity_report.json").exists());
    }

    #[tokio::test]
    async fn resource_planning_creates_artifacts() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(dir.path(), "diffusion models", true);
        let result = execute_resource_planning(Stage::ResourcePlanning, &ctx).await;

        assert_eq!(result.status, StageStatus::Done);
        assert!(result.artifacts.contains(&"resource_plan.json".to_owned()));
        assert!(result.artifacts.contains(&"schedule.json".to_owned()));
    }
}
