//! Phase B: Literature Discovery — SearchStrategy, LiteratureCollect,
//! LiteratureScreen, and KnowledgeExtract stage executors.

use crate::executor::{
    build_fallback_queries, utcnow_iso, StageContext, StageResult,
};
use crate::stages::{Stage, StageStatus};
use std::fs;

// ---------------------------------------------------------------------------
// SearchStrategy
// ---------------------------------------------------------------------------

/// Execute the SearchStrategy stage.
///
/// Produces `search_plan.yaml`, `sources.json`, and `queries.json`.
pub async fn execute_search_strategy(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let queries = build_fallback_queries(topic);

    // ---- search_plan.yaml --------------------------------------------------
    // Try LLM first; fall back to template if empty.
    let llm_plan = crate::executor::llm_generate(
        ctx,
        "You are a systematic literature search strategist for scientific research.",
        &format!(
            "Generate a comprehensive search plan in YAML format for the research topic:\n\n{}\n\n\
             Include: search strategies (keyword, citation snowballing, author search), \
             year filters, document type filters, and deduplication settings.",
            topic
        ),
        false,
    )
    .await;
    if !llm_plan.is_empty() {
        if let Err(e) = fs::write(stage_dir.join("search_plan.yaml"), &llm_plan) {
            return StageResult::failure(stage, format!("write search_plan.yaml: {e}"));
        }
        // Still write sources.json and queries.json from template
        let sources_json = serde_json::json!([
            {"id": "arxiv", "name": "arXiv", "url": "https://arxiv.org",
             "api_endpoint": "https://export.arxiv.org/api/query", "enabled": true,
             "categories": ["cs.LG", "cs.AI", "stat.ML", "physics", "q-bio"]},
            {"id": "semantic_scholar", "name": "Semantic Scholar",
             "url": "https://www.semanticscholar.org",
             "api_endpoint": "https://api.semanticscholar.org/graph/v1", "enabled": true},
            {"id": "pubmed", "name": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov",
             "api_endpoint": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils", "enabled": false}
        ]);
        if let Err(e) = fs::write(
            stage_dir.join("sources.json"),
            serde_json::to_string_pretty(&sources_json).unwrap_or_default(),
        ) {
            return StageResult::failure(stage, format!("write sources.json: {e}"));
        }
        let queries_json: Vec<serde_json::Value> = queries
            .iter()
            .enumerate()
            .map(|(i, q)| serde_json::json!({"id": format!("q{:02}", i + 1), "query": q,
                "source": "auto-generated", "priority": if i < 3 { "high" } else { "medium" }}))
            .collect();
        let queries_json_wrapper = serde_json::json!({"generated_at": utcnow_iso(),
            "topic": topic, "queries": queries_json});
        if let Err(e) = fs::write(
            stage_dir.join("queries.json"),
            serde_json::to_string_pretty(&queries_json_wrapper).unwrap_or_default(),
        ) {
            return StageResult::failure(stage, format!("write queries.json: {e}"));
        }
        return StageResult {
            stage,
            status: StageStatus::Done,
            artifacts: vec![
                "search_plan.yaml".to_owned(),
                "sources.json".to_owned(),
                "queries.json".to_owned(),
            ],
            error: None,
            decision: "proceed".to_owned(),
            elapsed_secs: 0.0,
        };
    }

    let queries_yaml: String = queries
        .iter()
        .map(|q| format!("  - \"{}\"", q.replace('"', "\\\"")))
        .collect::<Vec<_>>()
        .join("\n");

    let search_plan_yaml = format!(
        r#"# Search Plan
# Generated by SearchStrategy stage

topic: "{topic}"
generated_at: "{ts}"

search_strategies:
  - name: primary_keyword_search
    description: Direct keyword search using extracted query terms
    queries:
{queries_yaml}

  - name: citation_snowballing
    description: Forward and backward citation tracking from seed papers
    seed_papers: []
    max_depth: 2

  - name: author_search
    description: Search by influential authors in the field
    top_authors: []

filters:
  year_range:
    min: 2018
    max: 2025
  min_citations: 0
  languages:
    - en
  document_types:
    - journal_article
    - conference_paper
    - preprint

dedup:
  enabled: true
  fields:
    - doi
    - title_normalized
  similarity_threshold: 0.85

max_papers_per_query: 50
total_paper_cap: 500
"#,
        topic = topic,
        ts = utcnow_iso(),
        queries_yaml = queries_yaml,
    );

    if let Err(e) = fs::write(stage_dir.join("search_plan.yaml"), &search_plan_yaml) {
        return StageResult::failure(stage, format!("write search_plan.yaml: {e}"));
    }

    // ---- sources.json ------------------------------------------------------
    let sources_json = serde_json::json!([
        {
            "id": "arxiv",
            "name": "arXiv",
            "url": "https://arxiv.org",
            "api_endpoint": "https://export.arxiv.org/api/query",
            "enabled": true,
            "categories": ["cs.LG", "cs.AI", "stat.ML", "physics", "q-bio"]
        },
        {
            "id": "semantic_scholar",
            "name": "Semantic Scholar",
            "url": "https://www.semanticscholar.org",
            "api_endpoint": "https://api.semanticscholar.org/graph/v1",
            "enabled": true
        },
        {
            "id": "pubmed",
            "name": "PubMed",
            "url": "https://pubmed.ncbi.nlm.nih.gov",
            "api_endpoint": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
            "enabled": false
        }
    ]);

    if let Err(e) = fs::write(
        stage_dir.join("sources.json"),
        serde_json::to_string_pretty(&sources_json).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write sources.json: {e}"));
    }

    // ---- queries.json ------------------------------------------------------
    let queries_json: Vec<serde_json::Value> = queries
        .iter()
        .enumerate()
        .map(|(i, q)| {
            serde_json::json!({
                "id": format!("q{:02}", i + 1),
                "query": q,
                "source": "auto-generated",
                "priority": if i < 3 { "high" } else { "medium" }
            })
        })
        .collect();

    let queries_json_wrapper = serde_json::json!({
        "generated_at": utcnow_iso(),
        "topic": topic,
        "queries": queries_json
    });

    if let Err(e) = fs::write(
        stage_dir.join("queries.json"),
        serde_json::to_string_pretty(&queries_json_wrapper).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write queries.json: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec![
            "search_plan.yaml".to_owned(),
            "sources.json".to_owned(),
            "queries.json".to_owned(),
        ],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// LiteratureCollect
// ---------------------------------------------------------------------------

/// Execute the LiteratureCollect stage.
///
/// Produces `candidates.jsonl` with synthetic placeholder paper entries.
pub async fn execute_literature_collect(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let now = utcnow_iso();

    // Try LLM to generate candidate papers as JSONL; fall back to template.
    let llm_candidates = crate::executor::llm_generate(
        ctx,
        "You are a research librarian collecting scientific literature.",
        &format!(
            "Generate 5 representative placeholder paper records as JSONL (one JSON object per line) \
             for the research topic: {}\n\n\
             Each record must have fields: paper_id, title, authors (array), year, venue, abstract, \
             url, citations (int), relevance_score (0.0-1.0), source.",
            topic
        ),
        false,
    )
    .await;
    if !llm_candidates.is_empty() {
        if let Err(e) = fs::write(stage_dir.join("candidates.jsonl"), &llm_candidates) {
            return StageResult::failure(stage, format!("write candidates.jsonl: {e}"));
        }
        return StageResult {
            stage,
            status: StageStatus::Done,
            artifacts: vec!["candidates.jsonl".to_owned()],
            error: None,
            decision: "proceed".to_owned(),
            elapsed_secs: 0.0,
        };
    }

    // Generate placeholder candidate papers as JSONL
    let candidates = vec![
        serde_json::json!({
            "paper_id": "placeholder-001",
            "title": format!("A Survey of {}: Current Methods and Open Challenges", topic),
            "authors": ["A. Author", "B. Researcher", "C. Scientist"],
            "year": 2024,
            "venue": "NeurIPS",
            "abstract": format!("We present a comprehensive survey of {} methods, covering recent advances and open research problems.", topic),
            "url": "https://arxiv.org/abs/placeholder-001",
            "doi": null,
            "citations": 45,
            "relevance_score": 0.92,
            "retrieved_at": now,
            "source": "arxiv"
        }),
        serde_json::json!({
            "paper_id": "placeholder-002",
            "title": format!("Improving {} with Deep Learning Techniques", topic),
            "authors": ["D. Practitioner", "E. Engineer"],
            "year": 2023,
            "venue": "ICML",
            "abstract": format!("This paper proposes a novel deep learning approach for {} that achieves state-of-the-art results.", topic),
            "url": "https://arxiv.org/abs/placeholder-002",
            "doi": null,
            "citations": 120,
            "relevance_score": 0.88,
            "retrieved_at": now,
            "source": "semantic_scholar"
        }),
        serde_json::json!({
            "paper_id": "placeholder-003",
            "title": format!("Theoretical Foundations of {}", topic),
            "authors": ["F. Theorist"],
            "year": 2022,
            "venue": "Journal of Machine Learning Research",
            "abstract": format!("We establish theoretical guarantees for algorithms in {} and prove convergence bounds.", topic),
            "url": "https://arxiv.org/abs/placeholder-003",
            "doi": "10.XXXX/placeholder-003",
            "citations": 78,
            "relevance_score": 0.75,
            "retrieved_at": now,
            "source": "semantic_scholar"
        }),
        serde_json::json!({
            "paper_id": "placeholder-004",
            "title": format!("Efficient {} at Scale: Lessons from Large-Scale Deployment", topic),
            "authors": ["G. Practitioner", "H. Engineer", "I. Researcher"],
            "year": 2024,
            "venue": "ICLR",
            "abstract": format!("We report our experience scaling {} to production systems and share practical insights.", topic),
            "url": "https://arxiv.org/abs/placeholder-004",
            "doi": null,
            "citations": 33,
            "relevance_score": 0.71,
            "retrieved_at": now,
            "source": "arxiv"
        }),
        serde_json::json!({
            "paper_id": "placeholder-005",
            "title": format!("Benchmarking {} Methods: A Comprehensive Evaluation", topic),
            "authors": ["J. Benchmarker", "K. Evaluator"],
            "year": 2023,
            "venue": "arXiv",
            "abstract": format!("We provide a standardized benchmark suite for {} and evaluate 15 methods across 10 datasets.", topic),
            "url": "https://arxiv.org/abs/placeholder-005",
            "doi": null,
            "citations": 55,
            "relevance_score": 0.83,
            "retrieved_at": now,
            "source": "arxiv"
        }),
    ];

    let jsonl: String = candidates
        .iter()
        .map(|v| serde_json::to_string(v).unwrap_or_default())
        .collect::<Vec<_>>()
        .join("\n");

    if let Err(e) = fs::write(stage_dir.join("candidates.jsonl"), &jsonl) {
        return StageResult::failure(stage, format!("write candidates.jsonl: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec!["candidates.jsonl".to_owned()],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// LiteratureScreen (GATE)
// ---------------------------------------------------------------------------

/// Execute the LiteratureScreen stage.
///
/// Reads `candidates.jsonl`, filters papers by relevance score, and produces
/// `screened_papers.jsonl` and `exclusion_reasons.json`.
///
/// This is a GATE stage — if `ctx.auto_approve_gates` is false, returns
/// `BlockedApproval`.
pub async fn execute_literature_screen(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    // Read candidates
    let candidates_text = crate::executor::read_prior_artifact_pub(&ctx.run_dir, "candidates.jsonl")
        .unwrap_or_default();

    let mut screened: Vec<serde_json::Value> = Vec::new();
    let mut excluded: Vec<serde_json::Value> = Vec::new();

    for line in candidates_text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if let Ok(paper) = serde_json::from_str::<serde_json::Value>(line) {
            let score = paper
                .get("relevance_score")
                .and_then(|v| v.as_f64())
                .unwrap_or(0.0);

            if score >= 0.7 {
                let mut screened_paper = paper.clone();
                if let Some(obj) = screened_paper.as_object_mut() {
                    obj.insert("screening_status".to_owned(), serde_json::json!("included"));
                    obj.insert("screening_score".to_owned(), serde_json::json!(score));
                }
                screened.push(screened_paper);
            } else {
                let id = paper
                    .get("paper_id")
                    .and_then(|v| v.as_str())
                    .unwrap_or("unknown");
                excluded.push(serde_json::json!({
                    "paper_id": id,
                    "reason": "relevance_score_below_threshold",
                    "score": score,
                    "threshold": 0.7
                }));
            }
        }
    }

    // If no candidates were found, create fallback screened papers
    if screened.is_empty() && candidates_text.is_empty() {
        let topic = ctx.config.topic.as_str();
        let now = utcnow_iso();
        screened.push(serde_json::json!({
            "paper_id": "fallback-001",
            "title": format!("Key Paper on {}", topic),
            "authors": ["Template Author"],
            "year": 2024,
            "venue": "NeurIPS",
            "relevance_score": 0.90,
            "screening_status": "included",
            "retrieved_at": now,
            "abstract": format!("Placeholder paper on {} for pipeline testing.", topic)
        }));
    }

    // Write screened_papers.jsonl
    let screened_jsonl: String = screened
        .iter()
        .map(|v| serde_json::to_string(v).unwrap_or_default())
        .collect::<Vec<_>>()
        .join("\n");

    if let Err(e) = fs::write(stage_dir.join("screened_papers.jsonl"), &screened_jsonl) {
        return StageResult::failure(stage, format!("write screened_papers.jsonl: {e}"));
    }

    // Write exclusion_reasons.json
    let exclusion_json = serde_json::json!({
        "total_candidates": screened.len() + excluded.len(),
        "included": screened.len(),
        "excluded": excluded.len(),
        "exclusion_reasons": excluded
    });

    if let Err(e) = fs::write(
        stage_dir.join("exclusion_reasons.json"),
        serde_json::to_string_pretty(&exclusion_json).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write exclusion_reasons.json: {e}"));
    }

    if !ctx.auto_approve_gates {
        return StageResult {
            stage,
            status: StageStatus::BlockedApproval,
            artifacts: vec![
                "screened_papers.jsonl".to_owned(),
                "exclusion_reasons.json".to_owned(),
            ],
            error: None,
            decision: "awaiting_approval".to_owned(),
            elapsed_secs: 0.0,
        };
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec![
            "screened_papers.jsonl".to_owned(),
            "exclusion_reasons.json".to_owned(),
        ],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// KnowledgeExtract
// ---------------------------------------------------------------------------

/// Execute the KnowledgeExtract stage.
///
/// Reads screened papers and produces `knowledge_cards.json` and
/// `citation_map.json`.
pub async fn execute_knowledge_extract(stage: Stage, ctx: &StageContext) -> StageResult {
    let stage_dir = ctx.stage_dir(stage);
    if let Err(e) = fs::create_dir_all(&stage_dir) {
        return StageResult::failure(stage, format!("create stage dir: {e}"));
    }

    let topic = ctx.config.topic.as_str();
    let screened_text =
        crate::executor::read_prior_artifact_pub(&ctx.run_dir, "screened_papers.jsonl")
            .unwrap_or_default();

    // Try LLM to generate knowledge cards JSON; fall back to template.
    let llm_cards = crate::executor::llm_generate(
        ctx,
        "You are a scientific knowledge extraction specialist.",
        &format!(
            "Extract structured knowledge cards from the following screened papers for topic: {}\n\n\
             Screened papers (JSONL):\n{}\n\n\
             Return a JSON object with fields: topic, extracted_at, total_cards, cards (array). \
             Each card: card_id, paper_id, title, authors, year, key_contributions (array), \
             key_findings, limitations (array), relevance_tags (array).",
            topic,
            if screened_text.is_empty() { "(no screened papers available)" } else { &screened_text }
        ),
        true,
    )
    .await;
    if !llm_cards.is_empty() {
        if let Err(e) = fs::write(stage_dir.join("knowledge_cards.json"), &llm_cards) {
            return StageResult::failure(stage, format!("write knowledge_cards.json: {e}"));
        }
        let citation_map = serde_json::json!({"topic": topic, "nodes": [], "edges": []});
        if let Err(e) = fs::write(
            stage_dir.join("citation_map.json"),
            serde_json::to_string_pretty(&citation_map).unwrap_or_default(),
        ) {
            return StageResult::failure(stage, format!("write citation_map.json: {e}"));
        }
        return StageResult {
            stage,
            status: StageStatus::Done,
            artifacts: vec!["knowledge_cards.json".to_owned(), "citation_map.json".to_owned()],
            error: None,
            decision: "proceed".to_owned(),
            elapsed_secs: 0.0,
        };
    }

    let mut knowledge_cards: Vec<serde_json::Value> = Vec::new();
    let mut citation_edges: Vec<serde_json::Value> = Vec::new();

    for line in screened_text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if let Ok(paper) = serde_json::from_str::<serde_json::Value>(line) {
            let id = paper
                .get("paper_id")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown")
                .to_owned();
            let title = paper
                .get("title")
                .and_then(|v| v.as_str())
                .unwrap_or("Unknown Title")
                .to_owned();
            let authors = paper
                .get("authors")
                .cloned()
                .unwrap_or(serde_json::json!([]));
            let year = paper.get("year").and_then(|v| v.as_i64()).unwrap_or(0);
            let abstract_text = paper
                .get("abstract")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_owned();

            knowledge_cards.push(serde_json::json!({
                "card_id": format!("kc-{}", id),
                "paper_id": id,
                "title": title,
                "authors": authors,
                "year": year,
                "key_contributions": [
                    format!("Advances {} methodology", topic),
                    "Provides empirical validation",
                    "Open-sources implementation"
                ],
                "key_findings": abstract_text,
                "limitations": ["Limited to specific domain", "Computational cost not analyzed"],
                "relevance_tags": [topic, "methodology", "evaluation"],
                "extracted_at": utcnow_iso()
            }));

            // Simulate citation edges
            citation_edges.push(serde_json::json!({
                "source": id,
                "target": "background-work",
                "relationship": "builds_on"
            }));
        }
    }

    // If no prior screened papers, create template knowledge cards
    if knowledge_cards.is_empty() {
        knowledge_cards.push(serde_json::json!({
            "card_id": "kc-template-001",
            "paper_id": "template-001",
            "title": format!("Foundational Work on {}", topic),
            "authors": ["Template Author"],
            "year": 2023,
            "key_contributions": [
                format!("Establishes baseline for {}", topic),
                "Introduces key benchmark datasets",
                "Proposes evaluation metrics"
            ],
            "key_findings": format!("This template knowledge card covers foundational work in {}.", topic),
            "limitations": ["Template placeholder — replace with real extracted knowledge"],
            "relevance_tags": [topic, "baseline", "foundational"],
            "extracted_at": utcnow_iso()
        }));
    }

    // Write knowledge_cards.json
    let cards_json = serde_json::json!({
        "topic": topic,
        "extracted_at": utcnow_iso(),
        "total_cards": knowledge_cards.len(),
        "cards": knowledge_cards
    });

    if let Err(e) = fs::write(
        stage_dir.join("knowledge_cards.json"),
        serde_json::to_string_pretty(&cards_json).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write knowledge_cards.json: {e}"));
    }

    // Write citation_map.json
    let citation_map = serde_json::json!({
        "topic": topic,
        "nodes": knowledge_cards
            .iter()
            .map(|kc| serde_json::json!({"id": kc["paper_id"], "title": kc["title"]}))
            .collect::<Vec<_>>(),
        "edges": citation_edges
    });

    if let Err(e) = fs::write(
        stage_dir.join("citation_map.json"),
        serde_json::to_string_pretty(&citation_map).unwrap_or_default(),
    ) {
        return StageResult::failure(stage, format!("write citation_map.json: {e}"));
    }

    StageResult {
        stage,
        status: StageStatus::Done,
        artifacts: vec![
            "knowledge_cards.json".to_owned(),
            "citation_map.json".to_owned(),
        ],
        error: None,
        decision: "proceed".to_owned(),
        elapsed_secs: 0.0,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::executor::MolConfig;
    use std::collections::HashMap;
    use tempfile::TempDir;

    fn make_ctx(dir: &std::path::Path, topic: &str) -> StageContext {
        StageContext {
            run_dir: dir.to_owned(),
            run_id: "test".to_owned(),
            config: MolConfig {
                topic: topic.to_owned(),
                settings: HashMap::new(),
            },
            prior_artifacts: HashMap::new(),
            auto_approve_gates: true,
            llm: None,
        }
    }

    #[tokio::test]
    async fn search_strategy_creates_artifacts() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(dir.path(), "transformer attention mechanisms");
        let result = execute_search_strategy(Stage::SearchStrategy, &ctx).await;

        assert_eq!(result.status, StageStatus::Done);
        assert!(result.artifacts.contains(&"search_plan.yaml".to_owned()));
        assert!(result.artifacts.contains(&"queries.json".to_owned()));

        let stage_dir = ctx.stage_dir(Stage::SearchStrategy);
        let yaml_content = fs::read_to_string(stage_dir.join("search_plan.yaml")).unwrap();
        assert!(yaml_content.contains("topic:"));
        assert!(yaml_content.contains("queries"));
    }

    #[tokio::test]
    async fn literature_screen_blocks_without_auto_approve() {
        let dir = TempDir::new().unwrap();
        let mut ctx = make_ctx(dir.path(), "graph neural networks");
        ctx.auto_approve_gates = false;
        let result = execute_literature_screen(Stage::LiteratureScreen, &ctx).await;
        assert_eq!(result.status, StageStatus::BlockedApproval);
    }

    #[tokio::test]
    async fn literature_screen_passes_with_auto_approve() {
        let dir = TempDir::new().unwrap();
        let ctx = make_ctx(dir.path(), "graph neural networks");
        let result = execute_literature_screen(Stage::LiteratureScreen, &ctx).await;
        assert_eq!(result.status, StageStatus::Done);
    }
}
