[package]
name = "mol-engine"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
glob = { workspace = true }
serde_yaml = { workspace = true }
md-5 = { workspace = true }
walkdir = { workspace = true }
mol-common = { workspace = true }
mol-config = { workspace = true }
mol-llm = { workspace = true }
