[package]
name = "mol-web"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
scraper = { workspace = true }
lopdf = { workspace = true }
url = { workspace = true }
mol-common = { workspace = true }
mol-llm = { workspace = true }
