[package]
name = "mol-templates"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tera = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
mol-common = { workspace = true }
