//! Decision agent — analyses a paper draft and decides which figures to create.

use anyhow::Result;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tracing::debug;

use crate::base::{AgentContext, AgentPlan, AgentStepResult, BaseAgent};

// ---------------------------------------------------------------------------
// FigureRequest
// ---------------------------------------------------------------------------

/// How a figure should be produced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FigureKind {
    /// Data-driven chart generated by Python / matplotlib / TikZ.
    Code,
    /// Conceptual diagram or architectural image generated by Gemini.
    Image,
}

/// A single figure requested by the decision agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FigureRequest {
    /// Short identifier (e.g. `"fig_accuracy_curve"`).
    pub id: String,
    /// Human-readable title.
    pub title: String,
    /// Detailed description of what the figure should show.
    pub description: String,
    /// Which production strategy to use.
    pub kind: FigureKind,
    /// Optional LaTeX label for cross-referencing.
    pub label: Option<String>,
    /// Caption text for the paper.
    pub caption: String,
    /// Priority (lower = higher priority).
    pub priority: u32,
}

// ---------------------------------------------------------------------------
// DecisionAgent
// ---------------------------------------------------------------------------

/// Analyses the paper context and decides which figures need to be created.
pub struct DecisionAgent {
    /// Minimum number of figures to request.
    pub min_figures: usize,
    /// Maximum number of figures to request.
    pub max_figures: usize,
}

impl DecisionAgent {
    /// Create a new decision agent.
    pub fn new(min_figures: usize, max_figures: usize) -> Self {
        Self {
            min_figures,
            max_figures,
        }
    }

    /// Heuristically derive figure requests from the paper topic and results.
    fn derive_requests(
        &self,
        topic: &str,
        has_experiment_results: bool,
    ) -> Vec<FigureRequest> {
        let mut requests = Vec::new();

        if has_experiment_results {
            requests.push(FigureRequest {
                id: "fig_main_results".to_owned(),
                title: "Main Experimental Results".to_owned(),
                description: format!(
                    "Bar chart or table figure comparing the proposed method against baselines on the primary benchmark for topic '{topic}'"
                ),
                kind: FigureKind::Code,
                label: Some("fig:main_results".to_owned()),
                caption: "Comparison of our method against baselines on the primary benchmark.".to_owned(),
                priority: 1,
            });

            requests.push(FigureRequest {
                id: "fig_learning_curves".to_owned(),
                title: "Learning / Convergence Curves".to_owned(),
                description: "Line plot showing training and validation loss/metric over epochs.".to_owned(),
                kind: FigureKind::Code,
                label: Some("fig:learning_curves".to_owned()),
                caption: "Training convergence curves.".to_owned(),
                priority: 2,
            });
        }

        requests.push(FigureRequest {
            id: "fig_architecture".to_owned(),
            title: "Model Architecture Diagram".to_owned(),
            description: format!(
                "Conceptual diagram illustrating the architecture proposed for '{topic}'."
            ),
            kind: FigureKind::Image,
            label: Some("fig:architecture".to_owned()),
            caption: "Overview of the proposed model architecture.".to_owned(),
            priority: 3,
        });

        requests.push(FigureRequest {
            id: "fig_ablation".to_owned(),
            title: "Ablation Study".to_owned(),
            description: "Bar chart showing the contribution of each component via ablation.".to_owned(),
            kind: FigureKind::Code,
            label: Some("fig:ablation".to_owned()),
            caption: "Ablation study results.".to_owned(),
            priority: 4,
        });

        // Clamp to configured bounds.
        let n = requests.len().clamp(self.min_figures, self.max_figures);
        requests.truncate(n);
        requests
    }
}

#[async_trait]
impl BaseAgent for DecisionAgent {
    fn name(&self) -> &str {
        "decision"
    }

    async fn plan(&self, context: &AgentContext) -> Result<AgentPlan> {
        Ok(AgentPlan::new(
            "Figure decision",
            vec![
                format!("Analyse paper topic '{}'", context.topic),
                "Determine which figures are needed".to_owned(),
                format!(
                    "Request {}-{} figures (code and/or image)",
                    self.min_figures, self.max_figures
                ),
            ],
        ))
    }

    async fn run(&self, plan: &AgentPlan) -> Result<AgentStepResult> {
        debug!(plan = %plan.title, "DecisionAgent running");

        let topic = plan
            .metadata
            .get("topic")
            .and_then(|v| v.as_str())
            .unwrap_or("molecular property prediction")
            .to_owned();

        let has_results = plan
            .metadata
            .get("has_experiment_results")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        let requests = self.derive_requests(&topic, has_results);
        let code_count = requests.iter().filter(|r| r.kind == FigureKind::Code).count();
        let image_count = requests.iter().filter(|r| r.kind == FigureKind::Image).count();

        let output = format!(
            "Decision: {} figures requested ({} code, {} image).",
            requests.len(),
            code_count,
            image_count
        );

        Ok(AgentStepResult::ok(output).with_artifact("figure_requests", &requests))
    }
}
